apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: devops
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"
      numExecutors: 2
      scmCheckoutRetryCount: 2
      mode: NORMAL
      
    jobs:
      - script: |
          pipelineJob('wargame-web-deploy') {
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/kimbeomjun90/devsecops_full.git')
                      credentials('github-credentials')
                    }
                    branch('*/main')
                  }
                }
                scriptPath('Jenkins/pipeline/Jenkinsfile')
              }
            }
            triggers {
              cron('*/5 * * * *')
            }
          }
